Generic Enrichment Lookups
smartystreets/smartystreets-go-sdk pull request #35
Opened 2024-02-19 22:19 UTC by JacobMcKenzieSmarty

Added functionality to the us-enrichment-api to allow for generic lookups that return raw json as a byte slice. This will allow for future data sets to be added without needing to make an immediate change to the SDK.

2024-02-20 20:36 UTC, LandonSmarty requested changes
The code looks great! I am really glad you simplified the unmarshalResponse function for the generic lookup. Main thing here is just add tests and make the name consistent with the other structs.

2024-02-20 20:36 UTC, LandonSmarty commented on us-enrichment-api/lookup.go
> +func (g *genericLookup) unmarshalResponse(bytesResponse []byte, headers http.Header) error {
To keep consistency with the rest of the lookup structs, lets change the bytesResponse variable name to bytes.

2024-02-20 20:36 UTC, LandonSmarty commented on us-enrichment-api/lookup.go
> +func (g *genericLookup) unmarshalResponse(bytesResponse []byte, headers http.Header) error {
With the logic here, I would love to see a test in client_test.go to verify everything is working properly.

2024-02-21 15:18 UTC, LandonSmarty approved these changes
Everything looks great! Well done.

2024-02-21 16:59 UTC, smartybryan commented
The implementation looks good.  
I'm struggling with the name SendGenericLookup.  
I thought about SendLookup but it seems like it needs more. Maybe SendUniversalLookup, or SendGeneralLookup.  Hmm.

2024-02-22 19:18 UTC, smartykent commented
I agree with Bryan in both cases.  Some examples would be good.  I also wonder if we can just call it SendLookup.

2024-02-26 20:47 UTC, SmartyAdam approved these changes

2024-02-26 20:57 UTC, merged